name: Python request
on: push
jobs:
  Python-action-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Get Python version
        run: python -V
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 python-dotenv gspread oauth2client flake8
      - name: Run python test
        run: cd test && python -m unittest -v
        env:
          SEARCH_WORDS: ${{ secrets.SEARCH_WORDS }}
      - name: Run flake8 test
        run: flake8 --max-line-length 150 --per-file-ignores test/test_request.py:E402
